application: fast-news
version: 1
runtime: python27
api_version: 1
threadsafe: yes
module: tasks

handlers:

- url: /tasks/.*
  script: tasks.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: latest
- name: PIL
  version: latest
- name: ssl
  version: latest
- name: jinja2
  version: latest
